name: super_measurement
description: Dart package for converting various unit measurement with ease
version: 2.1.3
repository: https://github.com/devsdocs/super_measurement

environment:
  sdk: ^3.5.4

dependencies:

dev_dependencies:
  lint: ^2.8.0
  test: ^1.25.5
