name: super_measurement
description: Dart package for converting various unit measurement with ease
version: 2.0.3
repository: https://github.com/devsdocs/super_measurement

environment:
  sdk: ^3.5.4

dependencies:

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
