name: super_measurement
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.1

# Add regular dependencies here.
dependencies:
  reusable_tools: ^1.0.12
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
