name: super_measurement
description: Dart package for converting unit measurement
version: 1.0.8
repository: https://github.com/devsdocs/super_measurement

environment:
  sdk: ^3.1.1

dependencies:
  json_annotation: ^4.8.1
  reusable_tools: ^1.0.16

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lint: ^2.1.2
  test: ^1.21.0
