name: super_measurement
description: Dart package for converting unit measurement
version: 1.0.4
repository: https://github.com/devsdocs/super_measurement

environment:
  sdk: ^3.1.1

dependencies:
  reusable_tools: ^1.0.12

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
