on: [ push, pull_request ]
name: tests
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dart action
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Install dependencies
        run: dart pub get
      - name: Run tests & test coverage
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
